-- V6__init_schema.sql
-- Initial Schema for Orders, Sales, Inventory and Refunds

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(50) NOT NULL UNIQUE,
    supplier_id VARCHAR(50) NOT NULL,
    supplier_name VARCHAR(150) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) DEFAULT 'General',
    unit_price NUMERIC(12, 2) NOT NULL,
    tax_rate NUMERIC(5, 4) NOT NULL,
    stock_level INT NOT NULL DEFAULT 0,
    reserved_stock INT NOT NULL DEFAULT 0,
    region VARCHAR(100) DEFAULT 'Nairobi'
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(100) NOT NULL UNIQUE,
    invoice_number VARCHAR(100) NOT NULL UNIQUE,
    shop_owner_id VARCHAR(50) NOT NULL,
    shop_owner_name VARCHAR(150) NOT NULL,
    shop_owner_phone VARCHAR(50) NOT NULL,
    supplier_id VARCHAR(50) NOT NULL,
    supplier_name VARCHAR(150) NOT NULL,
    region VARCHAR(100) DEFAULT 'Nairobi',
    subtotal NUMERIC(12, 2) NOT NULL,
    tax_amount NUMERIC(12, 2) NOT NULL,
    delivery_charges NUMERIC(12, 2) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    payment_status VARCHAR(50) NOT NULL,
    amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    amount_outstanding NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    payment_reference VARCHAR(100),
    order_status VARCHAR(50) NOT NULL,
    dispatch_date TIMESTAMP,
    expected_delivery_date DATE,
    delivery_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    delivery_confirmed_at TIMESTAMP,
    delivery_confirmed_by VARCHAR(150),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    cancellation_reason VARCHAR(255),
    cancelled_at TIMESTAMP
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id VARCHAR(50) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    tax_rate NUMERIC(5, 4) NOT NULL,
    line_total NUMERIC(12, 2) NOT NULL,
    line_tax NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(50) NOT NULL,
    supplier_id VARCHAR(50) NOT NULL,
    order_number VARCHAR(100),
    movement_type VARCHAR(50) NOT NULL,
    quantity INT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    notes VARCHAR(255)
);

CREATE TABLE supplier_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id VARCHAR(50) NOT NULL,
    order_number VARCHAR(100) NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_reference VARCHAR(100) NOT NULL UNIQUE,
    e_tims_receipt_number VARCHAR(100) NOT NULL UNIQUE,
    supplier_invoice_number VARCHAR(100) NOT NULL,
    customer_id VARCHAR(50) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    tax_amount NUMERIC(12, 2) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    sale_date TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    linked_order_number VARCHAR(100)
);

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    product_id VARCHAR(50) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity_sold INT NOT NULL,
    quantity_refunded INT NOT NULL DEFAULT 0,
    unit_price NUMERIC(12, 2) NOT NULL,
    tax_rate NUMERIC(5, 4) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    tax_amount NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales (id) ON DELETE CASCADE
);

CREATE TABLE refund_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_number VARCHAR(100) NOT NULL UNIQUE,
    sale_reference VARCHAR(100) NOT NULL,
    e_tims_receipt_number VARCHAR(100) NOT NULL,
    supplier_invoice_number VARCHAR(100) NOT NULL,
    credit_note_number VARCHAR(100) NOT NULL,
    refund_subtotal NUMERIC(12, 2) NOT NULL,
    refund_tax_amount NUMERIC(12, 2) NOT NULL,
    refund_total_amount NUMERIC(12, 2) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    requested_by VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    reversed_linked_order_number VARCHAR(100)
);

CREATE TABLE refund_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_return_id BIGINT NOT NULL,
    product_id VARCHAR(50) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    tax_rate NUMERIC(5, 4) NOT NULL,
    refund_amount NUMERIC(12, 2) NOT NULL,
    tax_refund_amount NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_refund_items_refund FOREIGN KEY (refund_return_id) REFERENCES refund_returns (id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX idx_products_supplier ON products (supplier_id);
CREATE INDEX idx_orders_shop_owner ON orders (shop_owner_id);
CREATE INDEX idx_orders_supplier ON orders (supplier_id);
CREATE INDEX idx_orders_status ON orders (order_status);
CREATE INDEX idx_sales_receipt ON sales (e_tims_receipt_number);
CREATE INDEX idx_sales_invoice ON sales (supplier_invoice_number);
